### ISSUE TITLE
C.LUI instruction does not trigger an exception when rd=x0

### ISSUE THREAD

**Issue by vincen-dev** [OpenXiangShan/NEMU#635] opened 2024-11-05 08:49 UTC
**Describe the bug**

While testing **XiangShan** with the **NEMU** reference model, we observed inconsistent execution behavior of `C.LUI `instructions when the destination register (`rd`) is set to `x0`.

In the NEMU model, executing C.LUI with rd=x0 does not trigger an exception.
In the XiangShan processor, executing the same instruction results in an illegal instruction exception.

**To Reproduce**
```
.section .text
.globl _start
_start:

    xor t0,t0,t0
    .word 0xb7006001  #c.lui   zero, 0x0
    nop
    nop
```

**Error log or Screenshots**

![image](https://github.com/user-attachments/assets/a4d84873-4e7d-4028-98b2-974d71b62970)

![image](https://github.com/user-attachments/assets/fbf16d76-39ce-4ad5-9eee-c1da56bdd0bf)

**Necessary information on versions**
xiangshan:commit 7af39ad2ddb1305b2c4ddf4c3a9663a7c3615fa6
nemu:861f8d3187fa8a58e14d2394d56b28f1f434adc2

**Comment by NewPaulWalker** [comment] 2024-11-05 11:47
Thank you for your issue and I will handle it.

Additionally, it seems that you may have miscommunicated. I believe what you meant is that XiangShan caused an illegal instruction exception, but NEMU raised nothing, right? This is because, based on the log file you provided and my own testing, it was XiangShan that raised the illegal instruction exception, while NEMU did not.

> I tested the `c.lui s0, 0x0` (rd is not **x0**) instruction again, and the same result as the previous test example appeared. xiangshan did not cause an illegal instruction exception, but nemu caused an illegal instruction exception.

**Comment by NewPaulWalker** [comment] 2024-11-07 05:25
> In addition, I just tested the `c.jr zero` instruction and it seems to be ok.

Thank you for your attempt.
This issue has already been fixed by @lewislzh through a [PR](https://github.com/OpenXiangShan/NEMU/pull/645).
The root cause was a decoding error for the Zcmop extension instructions, where the lui instruction was mistakenly decoded as a Zcmop instruction.
This has now been resolved.

**Closed** 2024-11-08 09:35 UTC
