### ISSUE TITLE
Illegal Instruction Exception Triggered by Executing Unknown Instruction, Incorrect mtval Register Update

### ISSUE THREAD

**Issue by vincen-dev** [OpenXiangShan/NEMU#597] opened 2024-10-23 02:14 UTC
**Describe the bug**

When testing XiangShan using **NEMU** as a reference model, I encountered an issue where NEMU fails to correctly update the **mtval** register when handling an illegal instruction (**unknown**). 

The RISCV specification is as follows:
```
The mtval register can optionally also be used to return the faulting instruction bits on an illegal instruction exception (mepc points to the faulting instruction in memory). If mtval is written with a
nonzero value when an illegal-instruction exception occurs, then mtval will contain the shortest of:
• the actual faulting instruction
• the first ILEN bits of the faulting instruction
• the first MXLEN bits of the faulting instruction
The value loaded into mtval on an illegal-instruction exception is right-justified and all unused upper
bits are cleared to zero.
```

**Note**: This issue is different from https://github.com/OpenXiangShan/NEMU/issues/584. The previous issue is that when an illegal instruction exception is triggered, the mtval register contains the machine code of the previous instruction. However, this issue is not.

**To Reproduce**

Run the following command to execute the test image with NEMU as the reference model:

`./build/emu -b 0 -e 0 -i mtval.img --diff /xs-env/XiangShan/ready-to-run/riscv64-nemu-interpreter-so`

![image](https://github.com/user-attachments/assets/7257816d-d885-4949-bb37-105d983571f2)
![image](https://github.com/user-attachments/assets/13f3c5ce-3866-464b-922f-b8e0d04ae892)

**Expected behavior**

When an illegal instruction exception occurs, NEMU should set mtval to 0 or the code of the illegal instruction.

**Necessary information on versions**

Xiangshan:commit ea2894c8c273b00083141d9258b412ed910b28f9 (HEAD, origin/master, origin/HEAD)

Ready-to-run:commit 2ade2e3879e019f6400cb33efbb62513166d139b (HEAD, origin/master, origin/HEAD)

NEMU commit: 300b282c158dbd2d4bd23edf4f682b27a0d711be

**Comment by NewPaulWalker** [comment] 2024-10-24 04:13
This is not a bug in NEMU. It is because XiangShan incorrectly fetched instruction 0x0001061f from PC at 0x80085f7e.

This issue has been fixed in the latest master branch, and you can use the latest version of XiangShan for testing.

**Comment by lewislzh** [comment] 2024-10-24 04:41
Meanwhile, when using the new version of XiangShan to run this test, we encountered an M-mode double-trap, which caused a hang. 
We suspect there may be an issue with the test: like `mtvec` was not set at that time.
![image](https://github.com/user-attachments/assets/4d961709-6fdc-4e6f-90ba-71deccd37ce0)

**Closed** 2024-11-04 10:02 UTC
